### PR TITLE
Added Play and Pause functionality

### PR DESCRIPTION
**Pull request by justimagine09**

### CODE REVIEW

**Comment by nfriedly** [comment]
Looks good to me, thanks!

**Comment by justimagine09** [comment]
when they will tag a new release? Thanks!

**Comment by justimagine09** [comment]
> Looks good to me, thanks!

when will you guys tag a new release? Awesome Library btw! Thanks!

**Comment by justimagine09** [comment]
> Looks good to me, thanks!

when will you guys tag a new release? Awesome Library btw! Thanks!

**Comment by nfriedly** [comment]
It's now published to npm as v5.1.0!

(I also bumped the dependencies and fixed a couple of test issues that were causing things to fail locally and on CI)

**Comment by justimagine09** [comment]
Thank you so much! You are awesome!

**Comment by nfriedly** [comment]
Thank you :)

**Pull request merged**
