### PR TITLE
Add typescript type definitions

### LINKED ISSUE #39: Built-in TypeScript types for microphone-stream
### Is your feature request related to a problem? Please describe.
The package [microphone-stream](https://www.npmjs.com/package/microphone-stream) neither provides built-in types nor it's type definitions are available in DefinitelyTyped.
* The types field is not present in [package.json](https://github.com/saebekassebil/microphone-stream/blob/4af20529a204a97673a8968982eed17275ea7811/package.json).
* The npm package [@types/microphone-stream](https://www.npmjs.com/package/@types/microphone-stream) is not present.

Because of the missing TypeScript types, if microphone-stream is consumed in a TypeScript project the following error is shown:

TypeScript code:
```ts
import * as MicrophoneStream from "microphone-stream";
```

Error:
```console
Could not find a declaration file for module 'microphone-stream'. '/Users/trivikr/workspace/aws-sdk-js-notes-app/node_modules/microphone-stream/microphone-stream.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/microphone-stream` if it exists or add a new declaration (.d.ts) file containing `declare module 'microphone-stream';`ts(7016)
```

<details>
<summary>Screenshot</summary>

Screen Shot 2021-02-03 at 8 01 01 AM

</details>

### Describe the solution you'd like
Add built-in TypeScript types for microphone-stream.
* With TypeScript 3.7, TypeScript added support for [generating .d.ts files from JavaScript using JSDoc syntax](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html).
* [dts-gen](https://github.com/microsoft/dts-gen) creates starter TypeScript definition files for any module or library.

### Describe alternatives you've considered
To resolve this error, the TypeScript project consuming the package either have to:
* add `@ts-ignore` to ignore the missing types.
* add `@types/microphone-stream/index.d.ts` in the root of the project.

### Additional context
Refs: https://github.com/aws-samples/aws-sdk-js-notes-app/pull/7

### PR DESCRIPTION
**Pull request by trivikr**
Fixes: https://github.com/saebekassebil/microphone-stream/issues/39

### CODE REVIEW

**Review by nfriedly — APPROVED** [review]
Awesome! I'm going to try to make something that runs this automatically either pre-commit or pre-version (or maybe both)

**Comment by trivikr** [comment]
> I'm going to try to make something that runs this automatically either pre-commit

I'm currently running it on pretest, so that CI fails in the PR in case if there's any issue with types generation. It would definitely be helpful to run on precommit, as types would be generated and associated with respective commits in the source code :+1:

**Comment by nfriedly** [comment]
Got it! I added `husky` to run the tests as a pre-commit hook. So it now runs `tsc` and the tests before each commit and blocks the commit if either fails. I also added `prettier` while I was at it to get so nice automated formatting.

It should be released in v5.2.0 by CI shortly.

**Comment by trivikr** [comment]
> I also added prettier while I was at it to get so nice automated formatting.

This is amazing!
I use prettier in all my projects, and had to reluctantly disabled `"editor.formatOnSave": true,` while working on microphone-stream repo yesterday. It's great to see that prettier is now being used :+1:

**Pull request merged**
